server:
  port: 8989
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8096
spring:
  datasource:
    url: jdbc:mysql://149.88.64.85:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    redis:
      host: xxxxxxx
      password: xxxxxxx
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: xxxxxx
  secretKey: xxxxxxxx
  bucket: xxxxxx
  httpUrl: xxxxxxx
